
name: Java Testing

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: "*/5 * * * *"
jobs:
  build:
    cron:
    runs-on: ubuntuvm
    permissions: write-all
    steps:
    - name: checking out repository
      uses: actions/checkout@v4
    - name: Set up JDK 8
      uses: actions/setup-java@v4
      with:
        java-version: '8'
        distribution: 'adopt'
        cache: maven
    - name: Build with Maven and running test
      run: mvn clean test
    - name: Publish Test Report
      if: success() || failure()
      uses: ScaCap/action-surefire-report@v1.8.0
              
            
      
