
name: Deploy

on:
  workflow_run:
    workflows: Java 
    types: [completed]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Download artifact
        id: download-artifact
        uses: dawidd6/action-download-artifact@v8
        with:
          workflow: Java
          name: versioninfoartifact      
