
name: Deploy

on:
  workflow_run:
    workflows: Java Testing
    types: [completed]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Download artifact
        id: download-artifact
        uses: dawidd6/action-download-artifact@v6
        with:
          workflow: "Java Testing"
          name: versioninfoartifact
