
name: Deploy

on:
  workflow_run:
    workflows: Java Testing
    types: [completed]
  workflow_dispatch:  # Triggered manually
    inputs:    
      runid:
        description: "pass the run id of previous workflow success"
        required: true
        type: string      
jobs:
  build:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Download artifact
        id: download-artifact
        uses: dawidd6/action-download-artifact@v8
        with:
          workflow: "test.yml"
          name: versioninfoartifact      
          run_id: ${{ inputs.runid || '' }}
      - name: checking artifact
        run: |
           ls -la
           cat buildinfo.txt 
