
name: Java

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
    - name: checking vars
      run: | 
        ls -la 
        echo "This is " > buildinfo.txt
    - name: Upload buildinfo file as artifact
      uses: actions/upload-artifact@v4
      with:
        name: versioninfoartifact
        path: buildinfo.txt
        retention-days: 7
              
            
      
