
name: Deploy

on:
  workflow_run:
    workflows: Java 
    types: [completed]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Download artifact
        id: download-artifact
        uses: dawidd6/action-download-artifact@v8
        with:
          workflow: "test.yml"
          name: versioninfoartifact      
      - name: checking artifact
        run: |
           ls -la
           cat buildinfo.txt 
